/**
 * Report Generation Utilities for SmartAttend
 * Supports PDF, CSV, and Excel exports for all user roles
 */

import { jsPDF } from 'jspdf';

export interface ReportData {
  title: string;
  subtitle?: string;
  generatedAt: Date;
  generatedBy: string;
  period: {
    start: Date;
    end: Date;
    label: string;
  };
  data: any[];
  summary?: Record<string, any>;
}

export interface StudentReportData extends ReportData {
  studentId: string;
  studentName: string;
  courses: {
    courseCode: string;
    courseName: string;
    attendance: number;
    present: number;
    late: number;
    absent: number;
    total: number;
  }[];
  overallAttendance: number;
  grade: string;
}

export interface FacultyReportData extends ReportData {
  facultyId: string;
  facultyName: string;
  sessions: {
    sessionId: string;
    courseCode: string;
    courseName: string;
    date: string;
    time: string;
    totalStudents: number;
    present: number;
    late: number;
    absent: number;
    attendanceRate: number;
  }[];
  totalSessions: number;
  averageAttendance: number;
}

export interface AdminReportData extends ReportData {
  institution: string;
  departments: {
    name: string;
    totalStudents: number;
    totalFaculty: number;
    averageAttendance: number;
    courses: number;
  }[];
  overallStats: {
    totalStudents: number;
    totalFaculty: number;
    totalSessions: number;
    averageAttendance: number;
    attendanceTrend: 'up' | 'down' | 'stable';
  };
}

/**
 * Generate CSV content from report data
 */
export function generateCSV(reportData: ReportData): string {
  const { title, generatedAt, data } = reportData;
  
  // Header
  let csv = `${title}\n`;
  csv += `Generated: ${generatedAt.toLocaleString()}\n`;
  csv += `Period: ${reportData.period.label}\n\n`;
  
  if (data.length === 0) {
    return csv + 'No data available\n';
  }
  
  // Column headers
  const headers = Object.keys(data[0]);
  csv += headers.join(',') + '\n';
  
  // Data rows
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header];
      // Escape commas and quotes
      if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
        return `"${value.replace(/"/g, '""')}"`;
      }
      return value;
    });
    csv += values.join(',') + '\n';
  });
  
  return csv;
}

/**
 * Generate student attendance report
 */
export function generateStudentReport(data: StudentReportData): string {
  let report = `STUDENT ATTENDANCE REPORT\n`;
  report += `${'='.repeat(60)}\n\n`;
  
  report += `Student: ${data.studentName} (${data.studentId})\n`;
  report += `Period: ${data.period.label}\n`;
  report += `Generated: ${data.generatedAt.toLocaleString()}\n`;
  report += `Generated By: ${data.generatedBy}\n\n`;
  
  report += `OVERALL PERFORMANCE\n`;
  report += `${'-'.repeat(60)}\n`;
  report += `Overall Attendance: ${data.overallAttendance}%\n`;
  report += `Grade: ${data.grade}\n\n`;
  
  report += `COURSE BREAKDOWN\n`;
  report += `${'-'.repeat(60)}\n`;
  
  data.courses.forEach(course => {
    report += `\n${course.courseCode} - ${course.courseName}\n`;
    report += `  Attendance Rate: ${course.attendance}%\n`;
    report += `  Present: ${course.present} | Late: ${course.late} | Absent: ${course.absent}\n`;
    report += `  Total Sessions: ${course.total}\n`;
  });
  
  return report;
}

/**
 * Generate faculty session report
 */
export function generateFacultyReport(data: FacultyReportData): string {
  let report = `FACULTY SESSION REPORT\n`;
  report += `${'='.repeat(60)}\n\n`;
  
  report += `Faculty: ${data.facultyName} (${data.facultyId})\n`;
  report += `Period: ${data.period.label}\n`;
  report += `Generated: ${data.generatedAt.toLocaleString()}\n\n`;
  
  report += `SUMMARY\n`;
  report += `${'-'.repeat(60)}\n`;
  report += `Total Sessions: ${data.totalSessions}\n`;
  report += `Average Attendance: ${data.averageAttendance.toFixed(1)}%\n\n`;
  
  report += `SESSION DETAILS\n`;
  report += `${'-'.repeat(60)}\n`;
  
  data.sessions.forEach(session => {
    report += `\n${session.date} ${session.time} - ${session.courseCode}\n`;
    report += `  ${session.courseName}\n`;
    report += `  Present: ${session.present} | Late: ${session.late} | Absent: ${session.absent}\n`;
    report += `  Attendance Rate: ${session.attendanceRate.toFixed(1)}%\n`;
  });
  
  return report;
}

/**
 * Generate admin institutional report
 */
export function generateAdminReport(data: AdminReportData): string {
  let report = `INSTITUTIONAL ATTENDANCE REPORT\n`;
  report += `${'='.repeat(60)}\n\n`;
  
  report += `Institution: ${data.institution}\n`;
  report += `Period: ${data.period.label}\n`;
  report += `Generated: ${data.generatedAt.toLocaleString()}\n\n`;
  
  report += `OVERALL STATISTICS\n`;
  report += `${'-'.repeat(60)}\n`;
  report += `Total Students: ${data.overallStats.totalStudents}\n`;
  report += `Total Faculty: ${data.overallStats.totalFaculty}\n`;
  report += `Total Sessions: ${data.overallStats.totalSessions}\n`;
  report += `Average Attendance: ${data.overallStats.averageAttendance.toFixed(1)}%\n`;
  report += `Trend: ${data.overallStats.attendanceTrend.toUpperCase()}\n\n`;
  
  report += `DEPARTMENT BREAKDOWN\n`;
  report += `${'-'.repeat(60)}\n`;
  
  data.departments.forEach(dept => {
    report += `\n${dept.name}\n`;
    report += `  Students: ${dept.totalStudents} | Faculty: ${dept.totalFaculty}\n`;
    report += `  Courses: ${dept.courses}\n`;
    report += `  Average Attendance: ${dept.averageAttendance.toFixed(1)}%\n`;
  });
  
  return report;
}

/**
 * Download report as file
 */
export function downloadReport(content: string, filename: string, type: 'csv' | 'txt' = 'txt'): void {
  const blob = new Blob([content], { 
    type: type === 'csv' ? 'text/csv;charset=utf-8;' : 'text/plain;charset=utf-8;' 
  });
  
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * Generate PDF report using jsPDF
 */
export async function generatePDFReport(reportData: ReportData, type: 'student' | 'faculty' | 'admin'): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;
  
  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }
    
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin);
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
    yPosition += 3;
  };
  
  // Add header
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(reportData.title, pageWidth / 2, 20, { align: 'center' });
  
  yPosition = 40;
  doc.setTextColor(0, 0, 0);
  
  // Add metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (reportData.subtitle) {
    doc.text(reportData.subtitle, margin, yPosition);
    yPosition += 6;
  }
  doc.text(`Generated: ${reportData.generatedAt.toLocaleString()}`, margin, yPosition);
  yPosition += 6;
  doc.text(`Period: ${reportData.period.label}`, margin, yPosition);
  yPosition += 10;
  
  // Generate content based on type
  switch (type) {
    case 'student':
      const studentData = reportData as StudentReportData;
      
      // Overall Performance
      addText('OVERALL PERFORMANCE', 14, true);
      addText(`Overall Attendance: ${studentData.overallAttendance}%`);
      addText(`Grade: ${studentData.grade}`);
      yPosition += 5;
      
      // Course Breakdown
      addText('COURSE BREAKDOWN', 14, true);
      studentData.courses.forEach(course => {
        addText(`${course.courseCode} - ${course.courseName}`, 12, true);
        addText(`  Attendance Rate: ${course.attendance}%`);
        addText(`  Present: ${course.present} | Late: ${course.late} | Absent: ${course.absent}`);
        addText(`  Total Sessions: ${course.total}`);
        yPosition += 3;
      });
      break;
      
    case 'faculty':
      const facultyData = reportData as FacultyReportData;
      
      // Summary
      addText('SUMMARY', 14, true);
      addText(`Total Sessions: ${facultyData.totalSessions}`);
      addText(`Average Attendance: ${facultyData.averageAttendance.toFixed(1)}%`);
      yPosition += 5;
      
      // Session Details
      addText('SESSION DETAILS', 14, true);
      facultyData.sessions.slice(0, 20).forEach(session => {
        addText(`${session.date} ${session.time} - ${session.courseCode}`, 11, true);
        addText(`  ${session.courseName}`);
        addText(`  Present: ${session.present} | Late: ${session.late} | Absent: ${session.absent}`);
        addText(`  Attendance Rate: ${session.attendanceRate.toFixed(1)}%`);
        yPosition += 3;
      });
      break;
      
    case 'admin':
      const adminData = reportData as AdminReportData;
      
      // Overall Statistics
      addText('OVERALL STATISTICS', 14, true);
      addText(`Total Students: ${adminData.overallStats.totalStudents}`);
      addText(`Total Faculty: ${adminData.overallStats.totalFaculty}`);
      addText(`Total Sessions: ${adminData.overallStats.totalSessions}`);
      addText(`Average Attendance: ${adminData.overallStats.averageAttendance.toFixed(1)}%`);
      addText(`Trend: ${adminData.overallStats.attendanceTrend.toUpperCase()}`);
      yPosition += 5;
      
      // Department Breakdown
      addText('DEPARTMENT BREAKDOWN', 14, true);
      adminData.departments.forEach(dept => {
        addText(dept.name, 12, true);
        addText(`  Students: ${dept.totalStudents} | Faculty: ${dept.totalFaculty}`);
        addText(`  Courses: ${dept.courses}`);
        addText(`  Average Attendance: ${dept.averageAttendance.toFixed(1)}%`);
        yPosition += 3;
      });
      break;
  }
  
  // Add footer
  // Type assertion to access internal API
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages} | Generated by SmartAttend`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }
  
  // Return the PDF as a Blob
  return new Promise((resolve) => {
    const blob = doc.output('blob');
    resolve(blob);
  });
}

/**
 * Generate Excel-compatible CSV
 * @returns Blob containing the CSV data
 */
export function generateExcelCSV(reportData: ReportData): Blob {
  const csv = generateCSV(reportData);
  return new Blob([csv], { type: 'text/csv;charset=utf-8;' });
}

/**
 * Download a report file
 */
function downloadCSVReport(reportData: ReportData): void {
  const csv = generateCSV(reportData);
  const filename = `${reportData.title.replace(/\s+/g, '_')}_${Date.now()}.csv`;
  downloadReport(csv, filename, 'csv');
}

/**
 * Format date range for reports
 */
export function formatDateRange(start: Date, end: Date): string {
  const options: Intl.DateTimeFormatOptions = { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  };
  
  return `${start.toLocaleDateString('en-US', options)} - ${end.toLocaleDateString('en-US', options)}`;
}

/**
 * Calculate week number in semester
 */
export function getWeekNumber(date: Date, semesterStart: Date): number {
  const diffTime = Math.abs(date.getTime() - semesterStart.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return Math.ceil(diffDays / 7);
}

/**
 * Generate attendance summary statistics
 */
export function calculateAttendanceStats(records: any[]): {
  total: number;
  present: number;
  late: number;
  absent: number;
  rate: number;
} {
  const total = records.length;
  const present = records.filter(r => r.status === 'present').length;
  const late = records.filter(r => r.status === 'late').length;
  const absent = total - present - late;
  const rate = total > 0 ? (present / total) * 100 : 0;
  
  return { total, present, late, absent, rate };
}

/**
 * Generate weekly attendance breakdown
 */
export function generateWeeklyBreakdown(
  records: any[],
  semesterStart: Date,
  semesterEnd: Date
): Array<{
  week: number;
  label: string;
  start: Date;
  end: Date;
  sessions: number;
  attended: number;
  rate: number;
}> {
  const weeks: any[] = [];
  let currentWeekStart = new Date(semesterStart);
  let weekNumber = 1;
  
  while (currentWeekStart <= semesterEnd) {
    const weekEnd = new Date(currentWeekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    
    const weekRecords = records.filter(r => {
      const recordDate = new Date(r.timestamp || r.date);
      return recordDate >= currentWeekStart && recordDate <= weekEnd;
    });
    
    const attended = weekRecords.filter(r => r.status === 'present' || r.status === 'late').length;
    const sessions = weekRecords.length;
    const rate = sessions > 0 ? (attended / sessions) * 100 : 0;
    
    weeks.push({
      week: weekNumber,
      label: `Week ${weekNumber}`,
      start: new Date(currentWeekStart),
      end: weekEnd > semesterEnd ? semesterEnd : weekEnd,
      sessions,
      attended,
      rate
    });
    
    currentWeekStart.setDate(currentWeekStart.getDate() + 7);
    weekNumber++;
  }
  
  return weeks;
}

/**
 * Export functions for use in components
 */
export const ReportGenerator = {
  generateCSV,
  generateStudentReport,
  generateFacultyReport,
  generateAdminReport,
  generatePDFReport,
  generateExcelCSV,
  downloadReport,
  formatDateRange,
  getWeekNumber,
  calculateAttendanceStats,
  generateWeeklyBreakdown
};
